### ISSUE TITLE
MacOS: Gets stuck on music player

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/cookbook#1]
<img width="972" alt="Screenshot 2024-08-22 at 10 51 52 AM" src="https://github.com/user-attachments/assets/8fdd0006-5787-42bb-adf1-e6f7467868bc">

**Comment by bcardarella** [comment]
Can't even quit the LVN Go app, had to kill

**Comment by carson-katri** [comment]
Fixed on `main`
