### ISSUE TITLE
MacOS "hint" might need to get pushed down a bit, seems crowded

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/cookbook#2]
<img width="972" alt="Screenshot 2024-08-22 at 10 53 52 AM" src="https://github.com/user-attachments/assets/ef13bbf5-b37c-47f1-b9e0-bf5df2fea619">

**Comment by carson-katri** [comment]
This demo should also show multiple cards on the page (probably 3 like the app itself) on macOS and iPadOS.

**Comment by bcardarella** [comment]
@carson-katri would it make more sense to just do a macos specific template?

**Comment by carson-katri** [comment]
For some of these pages, yes. But for this one, it'd be simpler to just do an `attr` for the style.
